### ISSUE TITLE
Combine functionality by adding arguments

### ISSUE THREAD

**Issue by pat-s** [LinlinYin/mlr3vis#5] opened 2019-06-17 14:37 UTC
For example: `plotBMRBoxplotsMore()`. What this function does in contrast to `plotBMRBoxplots()` should be supported via an argument and document in the help page.

**Comment by LinlinYin** [comment] 2019-06-18 03:57
Thanks! `plotBMRBoxplots `is to reproduce function in mlr. `plotBMRBoxplotsMore` is a better function including more information in my opinion. Will think about if they can be merged into one.

**Comment by larskotthoff** [comment] 2019-06-19 15:38
Any progress on this @LinlinYin? It's great that you're thinking about this, but we need to make decisions here soon.

**Comment by LinlinYin** [comment] 2019-06-20 07:49
Please review the updates in new commit.

**Comment by larskotthoff** [comment] 2019-06-21 16:44
Can you please explain your thinking behind the changes? Why did you decide on this API? And please follow and apply the mlr style guide.

Finally, GSOC is a full-time commitment. If all you're doing for this are a few small commits every couple of days this is not going to work.

**Comment by LinlinYin** [comment] 2019-06-24 06:30
Hello, I was following the suggestion of integrating `plotBMRBoxplots() `and `plotBMRBoxplotsMore()` via an argument and document in the help page. And I also think current version contains more information, is more flexible, and can be consistent with the mlr version.
If you have better idea about this figure, would you please describe it more specifically?  Thanks!

**Comment by LinlinYin** [comment] 2019-06-24 07:16
Hello, I am sorry to know that you are not satisfied about progress of this project. I am working very hard on it. And in my opinion, the project works well till now. 

It looks like a little slow because: 
1. This is not a simple programming only project. The exactly needs of this project is uncertain. We need to read a lot of documents to learn the details and communicate and change the needs. You can find that we have made a lot of changes on the plotLearnerPrediction and plotBMRBoxplots functions. Each change takes a lot of time to propose, learn and programming.
2. We are working on different aspects of this project. You can find that among current six the issues, only two of them are about visualizations features. Four of the issues are about documents, project format, tests. They are all on different topics and will take more time to learn and work on.

In my opinion, the project will run faster in next a few days. After we set up the package well (documents, theme, …) and get familiar with the visualization ideas (know exactly what we need), we can focus on more about programming only and add more features/functions into this package. So I think we are in the right track.

To make it faster, it will be great if you can provide more detail instructions about features/functions need to be added (for example, making an exact figure of something), which will save me a lot of time in reading documents and learning different kinds of details.

**Closed as completed** 2021-02-15 21:27 UTC
